### ISSUE TITLE
Error when trying to use Meteor.loginwith<> feature

### ISSUE THREAD

**Issue by santteegt** [Urigo/meteor-client-bundler#28]
Hi,

I'm trying to use the Meteor loginWithFacebook feature on my app, but I'm getting the following error when calling the function:

`Error: Must pass options.rootUrl or set ROOT_URL in the server environment`

I have properly configured the loginWithFacebook service and also set the ROOT_URL environment variable before running the Meteor server.

What could be the issue ? Or due to the nature of the meteor-client bundler it isn't possible to use this feature ?

Regards

**Comment by darkbasic** [comment]
`meteor-client.config.json`:
```
{
  "runtime": {
    "DDP_DEFAULT_CONNECTION_URL": "http://domain.tld:3000",
    "ROOT_URL": "http://domain.tld:80"
  },
  "import": [

  ]
}
```

`package.json`:
```
    "scripts": {
        "api": "cd api && export ROOT_URL=http://domain.tld:80 && meteor run --mobile-server=http://domain.tld:80 --settings private/settings.json",
```

You will also need an `nginx` proxy. Have a look in the other bug reports or wait for the updated tutorial which will include Facebook auth.

**Comment by santteegt** [comment]
Hi @darkbasic 

What is the content of `private/settings.json` file you specify in one of the scripts on `package.json`? Is it related to some config for meteor facebook login ?.

I have already followed your instructions on  [#40](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/40) for the meteor-client.config.json and the nginx proxy but after logging in in facebook, I get the following error on meteor's server console

```
Error in OAuth Server: redirectUrl (http://192.168.100.2:8100/) is not on the same host as the app (http://192.168.100.2:3000/)
```
I'm running my ionic app on `http://192.168.100.2:8100/` and the meteor server on `http://192.168.100.2:3000/` (both locally)

My `meteor-client.config.json` config file is similar than yours, while my nginx.config is configured as follows:

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
       # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Gzip Settings
        ##

        gzip on;
        gzip_disable "msie6";

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;

server {
            listen      80;
            server_name simpleride-ec.com;

            location / {
                proxy_pass http://192.168.100.2:8100;
            }
            location /_oauth/facebook {
                proxy_pass http://192.168.100.2:3000;
            }
            location /packages {
                proxy_pass http://192.168.100.2:3000;
            }
        }
}
```

Hope you can help me with some guidance on how to get this thing working.

Thanks in advance.

Regards.

**Comment by darkbasic** [comment]
The new tutorial with fb auth is almost ready, stay tuned ;)

**Comment by santteegt** [comment]
@darkbasic please let me know when it becomes available (I'm a little bit in a hurry as my app need to go on production soon)

**Comment by darkbasic** [comment]
I just talked with Uri about it, it will probably become available tomorrow.

**Comment by darkbasic** [comment]
I pushed the new version, you can already find it in this repository. Soon I will publish it in the website too. Let me know if it works for you.

**Comment by santteegt** [comment]
@darkbasic I have followed the instructions from step 17.1 to 17.7 in order to test the facebook login functionality, but I'm still getting the following error:

```
Error in OAuth Server: redirectUrl (http://192.168.2.15:8100/) is not on the same host as the app (http://192.168.2.15:3000/)
```

I'm running the ionic app on `http://192.168.2.15:8100`, whereas the meteor server on `http://192.168.2.15:3000`. 

My `meteor-client.config.json` is configured as follows. Notice that my nginx proxy is on port 32768, which is forwading to the listening port 80 on a docker image.

```
{
  "runtime": {
    "DDP_DEFAULT_CONNECTION_URL": "http://192.168.2.15:32768",
    "ROOT_URL": "http://192.168.2.15:32768"
  },
  "import": [

  ]
}
```
Finally, in my `nginx.config` configuration file, the proxy is configured as follows:

```
server {
            listen      80;
            server_name 192.168.2.15;

            location / {
                proxy_pass http://192.168.2.15:8100;
            }
            location ~ ^/(_oauth|packages|ufs) {
                proxy_pass http://192.168.2.15:3000;
            }
            location /sockjs {
                proxy_pass http://192.168.2.15:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                error_page  500 502 503 504 /50x.html;

            location = /50x.html {
                root /usr/share/ngix/html;
            }
        }
```

Hope you can help me with some hints on how to solve that. I really appreciate your contribution with the tutorial.

Regards

**Comment by darkbasic** [comment]
Why did you set the port to `32768` in `meteor-client.config.json` and then you configured the `nginx` proxy to listen to port 80 (`listen      80;`)? Also you should really use domain names, because if I recall correctly Facebook doesn't allow you to use IP addresses (but you can use `localhost` in testing mode).

**Comment by santteegt** [comment]
Hi @darkbasic,

My nginx proxy is running on a Docker container and listening in port 80, and port 32768 is configured to forward requests from the host machine.

In the other hand, I was always being able to login to facebook through my app built with Meteor CLI and using local network IP addresses. You just have to add it to the valid OAuth redirect URIs through the facebook developer console.

**Comment by santteegt** [comment]
Hi,

I finally solved the issue by developing the server side of my app on a linux machine which is easier to open port 80. Previously, I was testing this on a docker container running on my Macbook Pro where it is not that easy to open port 80.
